from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import Doctor, Specialization

User = get_user_model()

class UserSerializer(serializers.ModelSerializer):
    profile_picture_url = serializers.SerializerMethodField()
    
    class Meta:
        model = User
        fields = ('id', 'username', 'email', 'first_name', 'last_name', 
                 'phone_number', 'role', 'profile_picture', 'profile_picture_url',
                 'avatar_url', 'is_verified')
    
    def get_profile_picture_url(self, obj):
        if obj.profile_picture and hasattr(obj.profile_picture, 'url'):
            request = self.context.get('request')
            if request:
                return request.build_absolute_uri(obj.profile_picture.url)
            return obj.profile_picture.url
        elif obj.avatar_url:
            return obj.avatar_url
        return None

class SpecializationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Specialization
        fields = '__all__'

class DoctorSerializer(serializers.ModelSerializer):
    user = UserSerializer(read_only=True)
    specialization = SpecializationSerializer(read_only=True)
    specialization_id = serializers.IntegerField(
        write_only=True, 
        required=False,
        allow_null=True
    )
    
    # Add doctor_id field
    doctor_id = serializers.CharField(read_only=True)
    
    # Add computed fields
    full_name = serializers.SerializerMethodField()
    email = serializers.SerializerMethodField()
    phone_number = serializers.SerializerMethodField()
    profile_picture_url = serializers.SerializerMethodField()
    
    # Add user fields for updates
    first_name = serializers.CharField(write_only=True, required=False, allow_blank=True)
    last_name = serializers.CharField(write_only=True, required=False, allow_blank=True)
    user_email = serializers.EmailField(write_only=True, required=False, allow_blank=True)
    phone = serializers.CharField(write_only=True, required=False, allow_blank=True)
    
    # Add specialization name field for updates
    specialization_name = serializers.CharField(write_only=True, required=False, allow_blank=True, source='specialization')
    
    class Meta:
        model = Doctor
        fields = [
            'id', 'doctor_id', 'user', 'specialization', 'specialization_id',
            'qualification', 'years_of_experience', 'consultation_fee',
            'bio', 'address', 'consultation_hours', 
            'is_available', 'is_verified', 'license_number',
            'profile_picture', 'created_at', 'updated_at', 'full_name',
            'rating', 'reviews_count', 'email', 'phone_number', 'profile_picture_url',
            # Add user fields for updates
            'first_name', 'last_name', 'user_email', 'phone', 'specialization_name'
        ]
        read_only_fields = ('doctor_id', 'user', 'created_at', 'updated_at', 
                           'profile_picture', 'rating', 'reviews_count')
        extra_kwargs = {
            'first_name': {'write_only': True},
            'last_name': {'write_only': True}, 
            'user_email': {'write_only': True},
            'phone': {'write_only': True},
            'specialization_name': {'write_only': True},
        }
    
    def get_full_name(self, obj):
        if obj.user:
            return f"{obj.user.first_name} {obj.user.last_name}"
        return "Unknown Doctor"
    
    def get_email(self, obj):
        return obj.user.email if obj.user else None
    
    def get_phone_number(self, obj):
        return obj.user.phone_number if obj.user else None
    
    def get_profile_picture_url(self, obj):
        if obj.profile_picture and hasattr(obj.profile_picture, 'url'):
            request = self.context.get('request')
            if request:
                return request.build_absolute_uri(obj.profile_picture.url)
            return obj.profile_picture.url
        elif obj.user and obj.user.profile_picture and hasattr(obj.user.profile_picture, 'url'):
            request = self.context.get('request')
            if request:
                return request.build_absolute_uri(obj.user.profile_picture.url)
            return obj.user.profile_picture.url
        elif obj.user and obj.user.avatar_url:
            return obj.user.avatar_url
        return None
    
    def create(self, validated_data):
        # Handle specialization_id properly
        specialization_id = validated_data.pop('specialization_id', None)
        
        # The doctor_id will be auto-generated by the model
        doctor = super().create(validated_data)
        
        if specialization_id:
            try:
                specialization = Specialization.objects.get(id=specialization_id)
                doctor.specialization = specialization
                doctor.save()
            except Specialization.DoesNotExist:
                pass
        
        return doctor
    
    def update(self, instance, validated_data):
        # Extract user fields
        user_fields = {}
        doctor_fields = {}
        
        # Separate user fields from doctor fields
        for field, value in validated_data.items():
            if field in ['first_name', 'last_name', 'user_email', 'phone']:
                if field == 'phone':
                    user_fields['phone_number'] = value  # Map phone to phone_number
                elif field == 'user_email':
                    user_fields['email'] = value  # Map user_email to email
                else:
                    user_fields[field] = value
            else:
                doctor_fields[field] = value
        
        # Handle specialization_id separately
        specialization_id = doctor_fields.pop('specialization_id', None)
        
        # Handle specialization name (string) - try to find or create specialization
        specialization_name = doctor_fields.pop('specialization', None)
        
        # Update user fields if any
        if user_fields and instance.user:
            for field, value in user_fields.items():
                setattr(instance.user, field, value)
            instance.user.save()
        
        # Update doctor fields
        doctor = super().update(instance, doctor_fields)
        
        # Handle specialization by ID
        if specialization_id is not None:
            if specialization_id:
                try:
                    specialization = Specialization.objects.get(id=specialization_id)
                    doctor.specialization = specialization
                    doctor.save()
                except Specialization.DoesNotExist:
                    raise serializers.ValidationError({
                        'specialization_id': 'Invalid specialization ID'
                    })
            else:
                doctor.specialization = None
                doctor.save()
        
        # Handle specialization by name
        elif specialization_name:
            try:
                # Try to find existing specialization
                specialization, created = Specialization.objects.get_or_create(
                    name=specialization_name,
                    defaults={'description': f'{specialization_name} specialization', 'is_active': True}
                )
                doctor.specialization = specialization
                doctor.save()
            except Exception as e:
                # If specialization handling fails, just continue without it
                pass
        
        return doctor

class DoctorCreateSerializer(serializers.ModelSerializer):
    specialization_id = serializers.PrimaryKeyRelatedField(
        queryset=Specialization.objects.all(),
        write_only=True,
        required=False,
        allow_null=True,
        source='specialization'
    )
    
    # Note: doctor_id is not in fields - it will be auto-generated
    
    class Meta:
        model = Doctor
        fields = [
            'specialization_id', 'license_number', 'qualification',
            'years_of_experience', 'consultation_fee', 'bio',
            'address', 'consultation_hours'
        ]
    
    def validate_license_number(self, value):
        if Doctor.objects.filter(license_number=value).exists():
            raise serializers.ValidationError(
                "A doctor with this license number already exists."
            )
        return value
    
    def create(self, validated_data):
        # Auto-assign user from request
        validated_data['user'] = self.context['request'].user
        
        # The doctor_id will be auto-generated by the model's save method
        return super().create(validated_data)

class DoctorRegistrationSerializer(serializers.Serializer):
    """Serializer for combined doctor registration"""
    # User fields
    username = serializers.CharField(required=True, max_length=150)
    email = serializers.EmailField(required=True)
    password = serializers.CharField(required=True, write_only=True, min_length=8)
    confirm_password = serializers.CharField(required=True, write_only=True)
    first_name = serializers.CharField(required=True, max_length=30)
    last_name = serializers.CharField(required=True, max_length=150)
    phone_number = serializers.CharField(required=False, max_length=15)
    
    # Doctor fields
    specialization_id = serializers.IntegerField(required=False, allow_null=True)
    license_number = serializers.CharField(required=True, max_length=50)
    qualification = serializers.CharField(required=True)
    years_of_experience = serializers.IntegerField(required=True, min_value=0)
    consultation_fee = serializers.DecimalField(required=True, max_digits=10, decimal_places=2)
    bio = serializers.CharField(required=False, allow_blank=True)
    address = serializers.CharField(required=False, allow_blank=True)
    consultation_hours = serializers.JSONField(required=False, default=dict)
    
    def validate(self, data):
        # Check if passwords match
        if data['password'] != data['confirm_password']:
            raise serializers.ValidationError({
                'confirm_password': 'Passwords do not match.'
            })
        
        # Check if username already exists
        if User.objects.filter(username=data['username']).exists():
            raise serializers.ValidationError({
                'username': 'Username already exists.'
            })
        
        # Check if email already exists
        if User.objects.filter(email=data['email']).exists():
            raise serializers.ValidationError({
                'email': 'Email already exists.'
            })
        
        # Check if license number already exists
        if Doctor.objects.filter(license_number=data['license_number']).exists():
            raise serializers.ValidationError({
                'license_number': 'A doctor with this license number already exists.'
            })
        
        return data
    
    def create(self, validated_data):
        # Separate user and doctor data
        user_data = {
            'username': validated_data['username'],
            'email': validated_data['email'],
            'password': validated_data['password'],
            'first_name': validated_data['first_name'],
            'last_name': validated_data['last_name'],
            'phone_number': validated_data.get('phone_number', ''),
            'role': 'doctor'  # Auto-assign doctor role
        }
        
        doctor_data = {
            'specialization_id': validated_data.get('specialization_id'),
            'license_number': validated_data['license_number'],
            'qualification': validated_data['qualification'],
            'years_of_experience': validated_data['years_of_experience'],
            'consultation_fee': validated_data['consultation_fee'],
            'bio': validated_data.get('bio', ''),
            'address': validated_data.get('address', ''),
            'consultation_hours': validated_data.get('consultation_hours', {})
        }
        
        # Create user
        user = User.objects.create_user(**user_data)
        
        # Create doctor profile
        doctor = Doctor.objects.create(
            user=user,
            **{k: v for k, v in doctor_data.items() if k != 'specialization_id'}
        )
        
        # Handle specialization
        if doctor_data.get('specialization_id'):
            try:
                specialization = Specialization.objects.get(id=doctor_data['specialization_id'])
                doctor.specialization = specialization
                doctor.save()
            except Specialization.DoesNotExist:
                pass
        
        return {
            'user': user,
            'doctor': doctor
        }