# Generated by Django 5.2.8 on 2025-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(choices=[('financial_hardship', 'Financial Hardship'), ('athletic_scholarship', 'Athletic Scholarship'), ('academic_scholarship', 'Academic Scholarship'), ('international_student', 'International Student Support'), ('emergency', 'Emergency Situation'), ('other', 'Other')], max_length=30)),
                ('reason', models.TextField()),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('student', 'Student Health Plan'), ('employee', 'Employee Health Plan'), ('faculty', 'Faculty Health Plan'), ('external', 'External Insurance')], max_length=20)),
                ('insurance_company', models.CharField(max_length=100)),
                ('policy_number_prefix', models.CharField(max_length=10)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('annual_deductible', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_annual_coverage', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('service_description', models.TextField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('university_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent to Student'), ('pending_insurance', 'Pending Insurance Approval'), ('partially_paid', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue'), ('waived', 'Fee Waived'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('student_account', 'Student Account'), ('insurance', 'Insurance'), ('waiver', 'Fee Waiver'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=9)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('student_account', 'Student Account'), ('insurance', 'Insurance'), ('waiver', 'Fee Waiver'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('consultation', 'Consultation'), ('laboratory', 'Laboratory Tests'), ('pharmacy', 'Pharmacy'), ('procedure', 'Medical Procedure'), ('emergency', 'Emergency Services'), ('vaccination', 'Vaccination'), ('health_check', 'Health Check-up')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student_discount', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('student_id_number', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
