# Generated by Django 5.2.8 on 2025-12-01 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentreminder_appointmentslot_and_more'),
        ('billing', '0002_initial'),
        ('labs', '0002_initial'),
        ('patients', '0003_alter_patient_options_patient_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_installments', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('debt_number', models.CharField(max_length=50, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incurred_date', models.DateField()),
                ('due_date', models.DateField()),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_verification', 'Pending Verification'), ('payment_plan', 'Payment Plan'), ('overdue', 'Overdue'), ('in_collections', 'In Collections'), ('cleared', 'Cleared'), ('waived', 'Waived')], default='active', max_length=25)),
                ('is_urgent', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-incurred_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('phd', 'PhD'), ('international', 'International Student'), ('exchange', 'Exchange Student')], max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('tuition_coverage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='studentinsurance',
            name='insurance_plan',
        ),
        migrations.AlterModelOptions(
            name='feewaiver',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['category_type', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='studentinsurance',
            options={'ordering': ['-is_verified', 'student'], 'verbose_name_plural': 'Student Insurances'},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_patient_ac2240_idx',
        ),
        migrations.RemoveField(
            model_name='feewaiver',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='student_insurance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='student_discount',
        ),
        migrations.RemoveField(
            model_name='studentinsurance',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentinsurance',
            name='student_id_number',
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partially_approved', 'Partially Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='student_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentinsurance',
            name='coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentinsurance',
            name='deductible_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentinsurance',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentinsurance',
            name='insurance_type',
            field=models.CharField(choices=[('university', 'University Health Plan'), ('private', 'Private Insurance'), ('government', 'Government Plan'), ('none', 'No Insurance')], default='university', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinsurance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='feewaiver',
            name='waiver_type',
            field=models.CharField(choices=[('financial_hardship', 'Financial Hardship'), ('academic_scholarship', 'Academic Scholarship'), ('athletic_scholarship', 'Athletic Scholarship'), ('international_student', 'International Student Support'), ('emergency', 'Emergency Situation'), ('university_fund', 'University Fund'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('student_account', 'Student Account'), ('insurance', 'Insurance'), ('bank_transfer', 'Bank Transfer'), ('waiver', 'Fee Waiver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent to Student'), ('pending_insurance', 'Pending Insurance'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.servicecategory'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('student_account', 'Student Account'), ('insurance', 'Insurance'), ('bank_transfer', 'Bank Transfer'), ('waiver', 'Fee Waiver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_type',
            field=models.CharField(choices=[('consultation', 'Doctor Consultation'), ('emergency', 'Emergency Care'), ('laboratory', 'Laboratory Tests'), ('pharmacy', 'Pharmacy'), ('procedure', 'Medical Procedure'), ('vaccination', 'Vaccination'), ('health_check', 'Health Check-up'), ('mental_health', 'Mental Health Services')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinsurance',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinsurance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'status'], name='billing_inv_student_e08f50_idx'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='student_debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='billing.studentdebt'),
        ),
        migrations.AddField(
            model_name='feewaiver',
            name='student_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.studentdebt'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.studentdebt'),
        ),
        migrations.DeleteModel(
            name='InsurancePlan',
        ),
        migrations.AddIndex(
            model_name='studentdebt',
            index=models.Index(fields=['debt_number'], name='billing_stu_debt_nu_9efb01_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdebt',
            index=models.Index(fields=['student', 'status'], name='billing_stu_student_43b91f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdebt',
            index=models.Index(fields=['due_date', 'status'], name='billing_stu_due_dat_408a61_idx'),
        ),
    ]
