# Generated by Django 5.2.8 on 2025-12-26 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentreminder_appointmentslot_and_more'),
        ('chat', '0003_chatparticipant_is_active_chatparticipant_role'),
        ('doctors', '0008_doctoravailability_doctorschedule_scheduleexception'),
        ('labs', '0003_enhance_lab_models'),
        ('patients', '0004_alter_patient_height_alter_patient_weight'),
        ('prescriptions', '0002_alter_medication_options_alter_prescription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=0)),
                ('messages_by_patient', models.IntegerField(default=0)),
                ('messages_by_doctor', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_file_size', models.BigIntegerField(default=0)),
                ('average_response_time', models.DurationField(blank=True, null=True)),
                ('peak_activity_hour', models.IntegerField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('sound_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('read_receipts', models.BooleanField(default=True)),
                ('typing_indicators', models.BooleanField(default=True)),
                ('last_seen', models.BooleanField(default=True)),
                ('auto_download_media', models.BooleanField(default=True)),
                ('auto_play_videos', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='is_pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='permissions',
            field=models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='write', max_length=20),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='typing_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='related_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('room_created', 'Chat Room Created'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('file_shared', 'File Shared'), ('prescription_shared', 'Prescription Shared'), ('lab_result_shared', 'Lab Result Shared'), ('appointment_shared', 'Appointment Shared'), ('room_archived', 'Room Archived'), ('room_closed', 'Room Closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('general', 'General Inquiry'), ('group', 'Group Chat')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('appointment', 'Appointment'), ('system', 'System Message'), ('emoji', 'Emoji')], default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['user', 'is_read'], name='chat_chatno_user_id_6494da_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['-created_at'], name='chat_chatno_created_90a1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat_room', 'is_active'], name='chat_chatpa_chat_ro_6084f1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'is_online'], name='chat_chatpa_user_id_35ed67_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['patient', 'doctor'], name='chat_chatro_patient_3dd504_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status', 'is_active'], name='chat_chatro_status_f38ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-last_activity'], name='chat_chatro_last_ac_7a98e6_idx'),
        ),
        migrations.AddField(
            model_name='chatanalytics',
            name='chat_room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chatsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(related_name='read_messages', through='chat.MessageReadStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'timestamp'], name='chat_messag_chat_ro_9355cd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='chat_messag_sender__b20cde_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'timestamp'], name='chat_messag_is_read_974b12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
    ]
