# Generated by Django 5.2.8 on 2025-12-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicationManagment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='medicationreminder',
            options={'ordering': ['reminder_time']},
        ),
        migrations.AddIndex(
            model_name='medicationdose',
            index=models.Index(fields=['medication', 'scheduled_time'], name='medicationM_medicat_39eb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationdose',
            index=models.Index(fields=['scheduled_time', 'is_taken'], name='medicationM_schedul_fb5116_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationreminder',
            index=models.Index(fields=['reminder_time', 'is_sent'], name='medicationM_reminde_46c4bd_idx'),
        ),
    ]
