# Generated by Django 5.2.8 on 2025-11-24 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('emergency', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='emergencyprotocol',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assignments', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='first_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_responder_emergencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='emergency_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='emergency.emergencyrequest'),
        ),
        migrations.AddField(
            model_name='emergencyresponseteam',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_responses', to='emergency.emergencyresponseteam'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_responses', to='emergency.emergencyresponseteam'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyprotocol',
            unique_together={('protocol_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['status', 'priority'], name='emergency_e_status_92f296_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['created_at'], name='emergency_e_created_229908_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyrequest',
            index=models.Index(fields=['patient', 'status'], name='emergency_e_patient_a06007_idx'),
        ),
    ]
