# Generated by Django 5.2.8 on 2025-12-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital_type', models.CharField(choices=[('general', 'General Hospital'), ('specialty', 'Specialty Hospital'), ('trauma_center', 'Trauma Center'), ('children', "Children's Hospital"), ('psychiatric', 'Psychiatric Hospital'), ('rehabilitation', 'Rehabilitation Hospital')], default='general', max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('has_emergency_department', models.BooleanField(default=True)),
                ('has_trauma_center', models.BooleanField(default=False)),
                ('trauma_level', models.CharField(blank=True, max_length=10)),
                ('has_helicopter_pad', models.BooleanField(default=False)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('icu_beds', models.IntegerField(default=0)),
                ('current_wait_time', models.IntegerField(default=0)),
                ('accepts_ambulances', models.BooleanField(default=True)),
                ('is_on_diversion', models.BooleanField(default=False)),
                ('operates_24_7', models.BooleanField(default=True)),
                ('emergency_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='emergency_contacts_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient_blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient_current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='patient_medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_id', models.CharField(max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic Life Support (BLS)'), ('advanced', 'Advanced Life Support (ALS)'), ('critical_care', 'Critical Care Transport'), ('air_ambulance', 'Air Ambulance'), ('bariatric', 'Bariatric Ambulance')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('transporting', 'Transporting'), ('at_hospital', 'At Hospital'), ('out_of_service', 'Out of Service'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('max_capacity', models.IntegerField(default=2)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('has_defibrillator', models.BooleanField(default=True)),
                ('has_cardiac_monitor', models.BooleanField(default=True)),
                ('make_model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin_number', models.CharField(max_length=17, unique=True)),
                ('fuel_level', models.DecimalField(decimal_places=1, default=100.0, max_digits=3)),
                ('mileage', models.IntegerField(default=0)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_crew', models.ManyToManyField(blank=True, related_name='crew_ambulances', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_ambulances', to=settings.AUTH_USER_MODEL)),
                ('paramedic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paramedic_ambulances', to=settings.AUTH_USER_MODEL)),
                ('base_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulances', to='emergency.hospital')),
            ],
            options={
                'ordering': ['ambulance_id'],
            },
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assignments', to='emergency.ambulance'),
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('call', 'Phone Call'), ('in_app', 'In-App Notification')], max_length=10)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to='emergency.emergencyrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
