# Generated by Django 5.2.8 on 2025-12-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentreminder_appointmentslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('checkup', 'Routine Checkup'), ('sick_visit', 'Sick Visit'), ('second_opinion', 'Second Opinion'), ('prescription_renewal', 'Prescription Renewal')], default='consultation', max_length=20),
        ),
    ]
