# Generated by Django 5.2.8 on 2025-12-27 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0008_doctoravailability_doctorschedule_scheduleexception'),
        ('patients', '0004_alter_patient_height_alter_patient_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('temperature', 'Temperature'), ('oxygen_saturation', 'Oxygen Saturation'), ('respiratory_rate', 'Respiratory Rate'), ('blood_sugar', 'Blood Sugar'), ('weight', 'Weight'), ('height', 'Height'), ('bmi', 'BMI')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('critical_min', models.FloatField(blank=True, null=True)),
                ('critical_max', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_vital_types',
            },
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('patient_summary', 'Patient Summary'), ('vital_trends', 'Vital Trends'), ('alert_summary', 'Alert Summary'), ('system_overview', 'System Overview')], max_length=50)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('data', models.JSONField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('is_shared_with_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'health_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientHealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checkup', models.DateTimeField(blank=True, null=True)),
                ('total_readings', models.IntegerField(default=0)),
                ('abnormal_readings', models.IntegerField(default=0)),
                ('active_alerts', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_summary', to='patients.patient')),
            ],
            options={
                'db_table': 'health_patient_summaries',
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('temperature', 'Temperature'), ('oxygen_saturation', 'Oxygen Saturation'), ('respiratory_rate', 'Respiratory Rate'), ('blood_sugar', 'Blood Sugar'), ('weight', 'Weight'), ('height', 'Height'), ('bmi', 'BMI')], max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('is_manual', models.BooleanField(default=True)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_vitals_recorded', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='patients.patient')),
            ],
            options={
                'db_table': 'health_vital_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='patients.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_health_alerts', to=settings.AUTH_USER_MODEL)),
                ('vital_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.vitalreading')),
            ],
            options={
                'db_table': 'health_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
