# Generated by Django 5.2.8 on 2025-12-19 19:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_options_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('50.0'), message='Height must be at least 50.0 cm.'), django.core.validators.MaxValueValidator(Decimal('250.0'), message='Height cannot exceed 250.0 cm.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('2.0'), message='Weight must be at least 2.0 kg.'), django.core.validators.MaxValueValidator(Decimal('300.0'), message='Weight cannot exceed 300.0 kg.')]),
        ),
    ]
