# Generated by Django 5.2.8 on 2025-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_doctors_doc_is_avai_0215a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
