# Generated by Django 5.2.8 on 2025-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_rating_doctor_reviews_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, help_text='Auto-generated sequential ID', max_length=15, null=True, verbose_name='Doctor ID'),
        ),
    ]
