# Generated by Django 5.2.8 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_add_doctor_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(db_index=True, default='TEMP-ID', editable=False, max_length=15, unique=True, verbose_name='Doctor ID'),
        ),
    ]
