# Generated by Django 5.2.8 on 2025-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_audience', models.CharField(choices=[('all_patients', 'All Patients'), ('all_doctors', 'All Doctors'), ('all_users', 'All Users'), ('specific_patients', 'Specific Patients'), ('specific_doctors', 'Specific Doctors'), ('custom_list', 'Custom List')], max_length=20)),
                ('custom_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('appointment', 'Appointment'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('billing', 'Billing'), ('emergency', 'Emergency'), ('chat', 'Chat Message'), ('system', 'System'), ('reminder', 'Reminder'), ('health_alert', 'Health Alert'), ('announcement', 'Announcement')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('channels', models.JSONField(default=list)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('short_message', models.CharField(blank=True, max_length=100)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('deep_link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_notifications', models.IntegerField(default=0)),
                ('email_sent', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('push_sent', models.IntegerField(default=0)),
                ('in_app_sent', models.IntegerField(default=0)),
                ('email_delivered', models.IntegerField(default=0)),
                ('sms_delivered', models.IntegerField(default=0)),
                ('push_delivered', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('click_through_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('appointment_notifications', models.BooleanField(default=True)),
                ('prescription_notifications', models.BooleanField(default=True)),
                ('lab_result_notifications', models.BooleanField(default=True)),
                ('billing_notifications', models.BooleanField(default=True)),
                ('emergency_notifications', models.BooleanField(default=True)),
                ('chat_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('reminder_notifications', models.BooleanField(default=True)),
                ('health_alert_notifications', models.BooleanField(default=True)),
                ('announcement_notifications', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('appointment_confirmation', 'Appointment Confirmation'), ('appointment_cancellation', 'Appointment Cancellation'), ('prescription_ready', 'Prescription Ready'), ('lab_result_ready', 'Lab Result Ready'), ('payment_due', 'Payment Due'), ('payment_confirmation', 'Payment Confirmation'), ('emergency_alert', 'Emergency Alert'), ('chat_message', 'Chat Message'), ('system_maintenance', 'System Maintenance'), ('health_tip', 'Health Tip'), ('medication_reminder', 'Medication Reminder')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('short_message', models.CharField(blank=True, max_length=100)),
                ('action_url_template', models.CharField(blank=True, max_length=500)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('default_channels', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('appointment', 'Appointment Reminder'), ('medication', 'Medication Reminder'), ('follow_up', 'Follow-up Reminder'), ('payment', 'Payment Reminder'), ('health_check', 'Health Check Reminder'), ('vaccination', 'Vaccination Reminder')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('repeat_frequency', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='once', max_length=20)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled', models.DateTimeField()),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_scheduled'],
            },
        ),
    ]
